// Mocks generated by Mockito 5.4.6 from annotations
// in guia_do_multiverso/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:guia_do_multiverso/data/datasources/character_remote_datasource.dart'
    as _i7;
import 'package:guia_do_multiverso/data/models/characters_response_model.dart'
    as _i4;
import 'package:guia_do_multiverso/domain/entities/characters_response_entity.dart'
    as _i3;
import 'package:guia_do_multiverso/domain/repositories/character_repository.dart'
    as _i2;
import 'package:guia_do_multiverso/domain/usecases/get_characters.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCharacterRepository_0 extends _i1.SmartFake
    implements _i2.CharacterRepository {
  _FakeCharacterRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCharactersResponseEntity_1 extends _i1.SmartFake
    implements _i3.CharactersResponseEntity {
  _FakeCharactersResponseEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCharactersResponseModel_2 extends _i1.SmartFake
    implements _i4.CharactersResponseModel {
  _FakeCharactersResponseModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetCharacters].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCharacters extends _i1.Mock implements _i5.GetCharacters {
  MockGetCharacters() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CharacterRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCharacterRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CharacterRepository);

  @override
  _i6.Future<_i3.CharactersResponseEntity> call(
    _i5.GetCharactersParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i6.Future<_i3.CharactersResponseEntity>.value(
              _FakeCharactersResponseEntity_1(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i6.Future<_i3.CharactersResponseEntity>);
}

/// A class which mocks [CharacterRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCharacterRemoteDataSource extends _i1.Mock
    implements _i7.CharacterRemoteDataSource {
  MockCharacterRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.CharactersResponseModel> getCharacters({
    String? url,
    String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCharacters, [], {#url: url, #status: status}),
            returnValue: _i6.Future<_i4.CharactersResponseModel>.value(
              _FakeCharactersResponseModel_2(
                this,
                Invocation.method(#getCharacters, [], {
                  #url: url,
                  #status: status,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.CharactersResponseModel>);
}
